[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  VITE_KAKAO_API_KEY = ""
  VITE_KAKAO_REST_API_KEY = ""
